application: oxnzbot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/xmpp/.*
  script: bot.APPLICATION

- url: .*
  script: capsid.app

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe
- xmpp_error

libraries:
- name: webapp2
  version: "2.5.2"
